import assert from 'node:assert/strict';
import {fresh,valid,resolve,nextDay,ending,migrate,zeroTick,retryGraduate,changeMood,addBalloons,rankRows,nameValid,storyChoice} from '../dist/engine.js';
import * as old from '../dist/core-engine.js';
for(const f of [2999,3000,3001])for(const h of [69,70])for(const l of [74,75]){const s={...fresh(),followers:f,hype:h,loyal:l};assert.equal(ending(s).id,f>=3000?'happy':h>=70&&l>=75?'kyu':'bad');}
let s=fresh();s.phase='plan';s.playerName='테스트';s.energy=0;zeroTick(s,89900);assert.equal(resolve(s,'clip',.5).phase,'result');zeroTick(s,100);let g=resolve(s,'clip',.5);assert.equal(g.phase,'graduated');assert(valid(g));assert.throws(()=>resolve(g,'clip',.5));assert.throws(()=>retryGraduate(g));
let late=fresh();late.phase='plan';late.playerName='테스트';for(let i=0;i<16;i++){late=nextDay(resolve(late,'rest',0));}late.energy=0;zeroTick(late,90000);g=resolve(late,'clip',.9);assert(valid(g));const retry=retryGraduate(g);assert(valid(retry));assert.equal(retry.day,16);assert.equal(retry.energy,40);assert.equal(retry.followers,late.followers);assert.equal(retry.log.length,16);assert.notEqual(retry.runId,g.runId);
let final=retry;for(let i=16;i<45;i++)final=nextDay(resolve(final,'rest',0));final.energy=0;zeroTick(final,120000);assert.equal(final.zeroEnergyActiveMs,0);assert.equal(resolve(final,'clip',1).phase,'result');final=nextDay(resolve(final,'clip',1));assert(valid(final));assert.equal(final.dailySnapshots.length,46);
let rested=resolve(s,'rest',0);assert.equal(rested.zeroEnergyActiveMs,0);
let m=fresh();m.phase='plan';addBalloons(m,50);assert.equal(m.mood,61);addBalloons(m,100);assert.equal(m.mood,63);addBalloons(m,500);assert.equal(m.mood,63);changeMood(m,100);assert.equal(m.dayMoodChange,15);changeMood(m,-100);assert.equal(m.dayMoodChange,-12);
assert(migrate(old.fresh()));assert(valid(migrate(old.fresh())));assert.equal(migrate({version:1}),null);assert(nameValid('큐티팬'));assert(!nameValid(''));assert(!nameValid('가'.repeat(13)));
const rows=rankRows([{followers:1,loyal:1,hype:1,mood:1},{followers:1,loyal:1,hype:1,mood:1},{followers:0,loyal:1,hype:1,mood:1}]);assert.deepEqual(rows.map(r=>r.rank),[1,1,3]);
const outcomes=[];for(const [name,score,mode] of [['balanced',.8,'mix'],['expert',1,'mix'],['low',.1,'repeat'],['rest',0,'rest']]){let s=fresh();s.phase='plan';for(let i=0;i<46;i++){s=storyChoice(s,0);const action=mode==='rest'?'rest':s.energy<25?'rest':mode==='repeat'?'game':['clip','game','up','sing','cafe'][i%5];s=resolve(s,action,score);assert(valid(s),name+' day '+i);s=nextDay(s);assert(valid(s));}outcomes.push({name,followers:s.followers,ending:ending(s).id});}console.log('PASS ending boundaries, graduation, restart, migration, mood caps, 46-day ledger, names, ties',outcomes);
