import {ensureAudience,online,ranking,GROUPS,TOPICS,tickAudience,contextChat,moderate,reply} from './audience.js?v=photo-sale-event-20260916';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const put=(el,html)=>{if(el&&el.innerHTML!==html)el.innerHTML=html;};
export function createAudienceUI({state,seeds,save,toast,fx,running,active,modal,onReaction=()=>{}}){
  const data=()=>ensureAudience(state(),seeds);
  const style=document.createElement('link');style.rel='stylesheet';style.href='audience.css?v=photo-sale-event-20260916';document.head.append(style);
  const dialog=document.createElement('dialog');dialog.id='audience-dialog';dialog.setAttribute('aria-label','시청자 관리');document.body.append(dialog);
  const actionMenu=document.createElement('div');actionMenu.className='audience-action-menu';actionMenu.hidden=true;actionMenu.setAttribute('role','menu');document.body.append(actionMenu);
  let tab='online',selectedGift='',lastState=null,last=performance.now(),saved=0,lastReplyWall=-Infinity,lastQch=Number(state().qch)||0;
  const react=out=>{if(out?.reaction)onReaction(out.reaction);lastQch=Number(state().qch)||0;};
  const countHTML=()=>`<button type="button" class="audience-count" data-audience="list" title="시청자 목록 보기">시청자 ${online(data()).length}명 <span aria-hidden="true">⌄</span></button><div class="audience-peek">${online(data()).slice(0,5).map(v=>`<span>${esc(v.name)}</span>`).join('')}<button type="button" data-audience="list">전체 시청자 목록 보기</button></div>`;
  function line(m){const balloon=['donation','photo-sale-balloon'].includes(m.kind),fresh=balloon&&data().time-m.at<10,gift=balloon?`<img class="chat-gift-icon" src="assets/donation-balloons.png" alt="별풍선 응원">`:'',tier=['new','fan','elite','host','system'].includes(m.tier)?m.tier:'system',viewer=m.viewerId&&data().people.find(v=>v.id===m.viewerId),user=viewer?`<button type="button" class="chat-user" data-chat-viewer="${esc(viewer.id)}" aria-haspopup="menu" title="${esc(viewer.name)} 시청자 관리">${esc(GROUPS[tier]||'시청자')} · ${esc(m.name)}</button>`:`<span class="chat-user">${esc(GROUPS[tier]|| (tier==='host'?'스트리머':'안내'))} · ${esc(m.name)}</span>`;return `<div class="chat-line chat-tier-${tier} ${fresh?'chat-balloon':''} ${m.kind==='photo-sale-balloon'?'chat-photo-sale':''} ${m.kind==='troll'?'audience-troll':''}" data-message-id="${esc(m.id)}">${gift}${user}<span>${esc(m.text)}</span></div>`;}
  function compactHTML(){return `<div class="ambient-chat audience-chat"><div class="ambient-chat-head">LIVE CHAT <span>●</span><div class="audience-counter">${countHTML()}</div></div><div data-audience-feed="compact" role="log" aria-live="off">${data().messages.slice(-3).map(line).join('')}</div></div>`;}
  function feedHTML(){return `<section class="chat-list audience-feed"><div class="audience-feed-head"><b>방송 채팅</b><button type="button" data-audience="list">시청자 목록 · 별풍 순위 · 차단 관리</button><button type="button" data-audience="reply">채팅하기</button></div><div data-audience-feed="full" role="log" aria-live="off">${data().messages.slice(-30).map(line).join('')}</div><small>메인 채팅과 같은 기록입니다. 시청자가 많으면 채팅이 빨라집니다.</small></section>`;}
  function context(kind,topic,detail=''){contextChat(state(),kind,topic,detail);if(kind==='photo-sale-balloon')fx('byulpoong');update();}
  function replyHTML(){const a=data();const gifts=a.gifts.filter(g=>!g.thanked&&a.time-g.at<=60&&!a.people.find(v=>v.id===g.viewerId)?.blocked).slice(-8).reverse();return `<form id="audience-reply"><label>후원 답변 대상<select name="gift"><option value="">일반 채팅</option>${gifts.map(g=>`<option value="${g.id}" ${selectedGift===g.id?'selected':''}>${esc(a.people.find(v=>v.id===g.viewerId)?.name)} · 별풍선 ${g.amount}개 · 후원 당시 ${esc(g.groupAtGift||GROUPS[g.tierAtGift]||'시청자')}</option>`).join('')}</select></label><label>큐티섹시의 답변<input name="message" maxlength="100" placeholder="따뜻한 답변을 보내 주세요" autocomplete="off"></label><div class="audience-buttons"><button type="button" data-quick="ㅍㄴㅍㄴ">ㅍㄴㅍㄴ</button><button type="button" data-quick="ㅇㅇㄱ">ㅇㅇㄱ</button><button type="submit">보내기</button></div><small>후원 당시 등급과 별풍선 수량을 확인하고 알맞은 인사를 선택해 주세요.</small></form>`;}
  function openActionMenu(button){const id=button.dataset.chatViewer,v=data().people.find(p=>p.id===id);if(!v)return;const gift=data().gifts.filter(g=>g.viewerId===id&&!g.thanked&&data().time-g.at<=60&&!v.blocked).at(-1);const host=button.closest('dialog')?.open?button.closest('dialog'):document.body;if(actionMenu.parentElement!==host)host.append(actionMenu);actionMenu.innerHTML=`<strong>${esc(v.name)}</strong><button type="button" role="menuitem" data-chat-action="kick" data-viewer="${esc(id)}">강퇴</button><button type="button" role="menuitem" data-chat-action="block" data-viewer="${esc(id)}">차단</button><button type="button" role="menuitem" data-chat-action="reply" data-viewer="${esc(id)}" data-gift="${esc(gift?.id||'')}">별풍 리액션</button>`;actionMenu.hidden=false;const r=button.getBoundingClientRect(),w=actionMenu.offsetWidth||190,h=actionMenu.offsetHeight||150;actionMenu.style.left=Math.max(8,Math.min(r.left,innerWidth-w-8))+'px';actionMenu.style.top=Math.max(8,Math.min(r.bottom+6,innerHeight-h-8))+'px';actionMenu.querySelector('button')?.focus();}
  function closeActionMenu(){actionMenu.hidden=true;actionMenu.innerHTML='';}
  function paintDialog(){const a=data(),list=tab==='rank'?ranking(a):tab==='blocked'?a.people.filter(v=>v.blocked):tab==='kicked'?(a.kicks||[]):online(a);dialog.innerHTML=`<header><div><span class="eyebrow">LIVE AUDIENCE</span><h2>시청자와 함께하는 방송</h2></div><button type="button" data-audience="close" aria-label="시청자 관리 닫기">×</button></header><nav>${[['online',`접속 ${online(a).length}명`],['rank','별풍 TOP 20'],['blocked',`차단 ${a.people.filter(v=>v.blocked).length}명`],['kicked',`강퇴 기록 ${(a.kicks||[]).length}건`],['reply','답변하기']].map(([id,title])=>`<button type="button" data-audience-tab="${id}" aria-pressed="${tab===id}">${title}</button>`).join('')}</nav><p class="audience-help">${tab==='rank'?'전체 명부의 누적 후원 상위 20명이 열혈팬클럽입니다. 기존 회원의 시작 후원 이력이 포함됩니다.':tab==='kicked'?'강퇴일자와 처리 사유를 확인하는 기록입니다. 이 탭에서는 강퇴·차단 버튼을 표시하지 않습니다.':tab==='blocked'?'차단 해제 시 실제 차감했던 즐겨찾기를 복원하고 다시 입장합니다.':tab==='reply'?'답변과 후원은 두 채팅창에 같은 기록으로 표시됩니다.':'현재 접속 인원과 아래 목록 수는 같습니다. 목록을 보는 동안 방송·미니게임 시간이 멈춥니다.'}</p>${tab==='reply'?replyHTML():`<div class="audience-roster" role="list">${list.map((v,i)=>tab==='kicked'?`<div class="audience-row" role="listitem"><div><strong>${esc(v.name)}</strong><small>강퇴일 ${esc(String(v.day+1))}일 · 사유: ${esc(v.reason)}</small><small>${v.wrong?'오판 가능성 있음 · ':''}방송 시간 ${Math.floor(v.at)}초에 처리</small></div></div>`:`<div class="audience-row" role="listitem" data-viewer-id="${v.id}"><div><strong>${tab==='rank'?`${i+1}. `:''}${esc(v.name)}</strong><small>${GROUPS[v.tier]} · ${v.blocked?'차단':v.online?'접속':'오프라인'} · 누적 🎈${v.donated}</small><small>${v.abuseUntil>a.time?'⚠ 최근 악플 · ':''}관심: ${v.interests.map(t=>TOPICS[t]).join(', ')}</small></div><div class="audience-buttons">${tab==='rank'?'':v.blocked?`<button data-moderate="unblock" data-viewer="${v.id}">차단 해제</button>`:`${v.online?`<button data-moderate="kick" data-viewer="${v.id}">강퇴</button>`:''}<button data-moderate="block" data-viewer="${v.id}">차단</button>`}</div></div>`).join('')||'<p>해당 시청자가 없어요.</p>'}</div>`}<p id="audience-status" role="status"></p><details class="audience-rules"><summary>방송 운영 규칙 보기</summary><p>일반 강퇴: 충성도 −1·화제성 −1. 최근 악플 관리: 충성도 +1·화제성 −1·기분 +1. 각 효과는 하루 최대 4명, 같은 유저는 하루 한 번만 반영됩니다.</p><p>차단: 즐겨찾기 −1(실제 차감량만 해제 시 복원). 강퇴자는 방송 시간 45~75초 후 재입장합니다. 악플 방치: 충성도 −1·화제성 +1·기분 −2, 하루 최대 3회. 큐창 스탯이 25 이상이면 악플 유입과 즐겨찾기 이탈이 증가합니다.</p><p>가상 방송 게임입니다. 실제 SOOP 계정·시청자·결제와 연결되지 않습니다.</p></details>`;}
  function show(which='online',gift=''){tab=which;selectedGift=gift;paintDialog();window.dispatchEvent(new Event('blur'));if(!dialog.open)dialog.showModal();}
  function close(){if(dialog.open)dialog.close();last=performance.now();}
  document.addEventListener('click',e=>{const user=e.target.closest('[data-chat-viewer]');if(user){e.preventDefault?.();openActionMenu(user);return;}if(!actionMenu.hidden&&!e.target.closest('.audience-action-menu'))closeActionMenu();const b=e.target.closest('[data-audience]');if(!b)return;const k=b.dataset.audience;if(k==='close')close();else show(k==='reply'?'reply':'online');});
  actionMenu.addEventListener('click',e=>{const b=e.target.closest('[data-chat-action]');if(!b)return;const action=b.dataset.chatAction,id=b.dataset.viewer;if(action==='reply'){closeActionMenu();show('reply',b.dataset.gift||'');return;}const out=moderate(state(),id,action);react(out);save();closeActionMenu();update();toast(out.message);});
  dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.audienceTab){tab=b.dataset.audienceTab;paintDialog();return;}
    if(b.dataset.moderate){const top=dialog.querySelector('.audience-roster')?.scrollTop||0;const out=moderate(state(),b.dataset.viewer,b.dataset.moderate);react(out);save();paintDialog();dialog.querySelector('.audience-roster')?.scrollTo(0,top);dialog.querySelector('#audience-status').textContent=out.message;update();return;}
    if(b.dataset.quick){const f=dialog.querySelector('form');f.elements.message.value=b.dataset.quick;f.requestSubmit();}
  });
  dialog.addEventListener('submit',e=>{if(e.target.id!=='audience-reply')return;e.preventDefault();if(performance.now()-lastReplyWall<2000){dialog.querySelector('#audience-status').textContent='답변은 2초 간격으로 보낼 수 있어요.';return;}const f=e.target,out=reply(state(),f.elements.message.value,f.elements.gift.value);react(out);if(out.ok){lastReplyWall=performance.now();save();close();toast(out.message);}else{dialog.querySelector('#audience-status').textContent=out.message;}});
  // Keep shortcuts from triggering games behind the top-layer management dialog.
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!actionMenu.hidden){closeActionMenu();return;}if(dialog.open)e.stopPropagation();},true);
  document.addEventListener('keyup',e=>{if(dialog.open)e.stopPropagation();},true);
  dialog.addEventListener('close',()=>{last=performance.now();});
  function update(){const a=data();document.querySelectorAll('.audience-counter').forEach(el=>put(el,countHTML()));document.querySelectorAll('[data-audience-feed]').forEach(el=>{const full=el.dataset.audienceFeed==='full',tail=el.scrollHeight-el.scrollTop-el.clientHeight<36;put(el,a.messages.slice(full?-30:-3).map(line).join(''));if(tail||!full)el.scrollTop=el.scrollHeight;});
    const stats=document.querySelector('.stats');if(stats){let q=stats.querySelector('.qch-stat');if(!q){q=document.createElement('div');q.className='stat qch-stat';q.innerHTML='<div class="statline"><span>큐창 실수</span><span class="qch-value"></span></div><div class="progress"><span></span></div>';stats.insertBefore(q,stats.querySelector(':scope > .note'));}const value=Math.round(state().qch||0);const valueNode=q.querySelector('.qch-value')||q.querySelector('.statline > span:last-child');put(valueNode,`${value}<span class="label"> / 100</span>`);const bar=q.querySelector('.progress span');if(bar)bar.style.width=value+'%';}
    if((active()||state().phase==='result'&&modal.querySelector('.result-number'))&&modal.open&&!modal.querySelector('.audience-mini')){const panel=document.createElement('details');panel.className='audience-mini';panel.open=true;panel.innerHTML=`<summary>방송 채팅 · 관리 / 답변 <span class="audience-counter">${countHTML()}</span></summary><div data-audience-feed="mini" role="log" aria-live="off">${a.messages.slice(-3).map(line).join('')}</div><button type="button" data-audience="reply">후원 답변</button>`;modal.append(panel);}
    const labels=['mood','energy','hype','loyal','favorites'];document.querySelectorAll('.stats > .stat').forEach((el,i)=>{const value=state()[labels[i]];const span=el.querySelector('.statline > span:last-child');if(span&&Number.isFinite(value))put(span,`${value}<span class="label"> / 100</span>`);});
    const total=document.querySelector('.follower-wrap .note');if(total)put(total,`모은 별풍선 ${Math.round(state().balloons||0).toLocaleString('ko-KR')}개 · 판매한 방셀 ${(state().photoAlbum||[]).length}/10종`);
  }
  function giftEvent(g){const a=data(),v=a.people.find(v=>v.id===g.viewerId);g.reactionOffered=true;fx('byulpoong');if(active()||modal.open){toast(`🎈 ${v.name}님 별풍선 ${g.amount}개! 채팅에서 답변할 수 있어요.`);return;}
    show('reply',g.id);const p=document.createElement('p');p.className='audience-gift-notice';p.textContent=`🎈 ${v.name}님이 별풍선 ${g.amount}개를 보냈습니다!`;dialog.querySelector('nav').after(p);
  }
  setInterval(()=>{const now=performance.now(),dt=Math.min(2,(now-last)/1000);last=now;const s=state();data();if(lastState!==s){lastState=s;if(dialog.open)close();}
    const result=tickAudience(s,dt,{running:document.visibilityState==='visible'&&(!dialog.open||tab==='reply')&&running()});const qch=Number(s.qch)||0;if(qch>lastQch)onReaction('mistake');lastQch=qch;update();if(result.gifts.length){save();saved=0;}for(const g of result.gifts)giftEvent(g);if(result.changed&&(saved+=dt)>=5){saved=0;save();}
  },1000);
  document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)save();});window.addEventListener('pagehide',save);
  return {compactHTML,feedHTML,context,update,paused:()=>dialog.open,viewers:()=>online(data()).map(v=>({...v,type:GROUPS[v.tier]}))};
}
