import {PHOTOS,FANARTS,FANART_PLACEHOLDER,photosForDay,photoRewards} from './gallery-data.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const PHOTO_POSES=['heart','smile','v'];
export const photoOrderSrc=(id,pose)=>`assets/gallery/orders/${id}-${pose}.webp`;
export function artHTML(item){return `<figure class="gallery-figure"><img src="${item.ready?item.src:FANART_PLACEHOLDER}" alt="${escape(item.ready?item.description:'팬아트 이미지 준비 중')}" data-gallery-img><figcaption>${escape(item.title)}${item.ready?'':' · 이미지 준비 중'}</figcaption></figure>`;}
export function guardImages(root){root.querySelectorAll('[data-gallery-img]').forEach(img=>{img.onerror=()=>{img.onerror=null;img.src=FANART_PLACEHOLDER;img.alt='팬아트 이미지를 불러오지 못했습니다.';img.closest('figure').querySelector('figcaption').textContent='이미지 준비 중';};});}
export function showArtwork(modal,item,onClose){
 const previous=document.activeElement;const overlay=document.createElement('div');overlay.className='art-overlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label',item.title);
 overlay.innerHTML=`<section class="art-viewer"><h3>${escape(item.title)}</h3>${artHTML(item)}<p>감상 중에는 미니게임 시간이 멈춥니다.</p><button class="primary" data-art-close>감상 마치기</button></section>`;modal.append(overlay);guardImages(overlay);
 const button=overlay.querySelector('button');button.focus();let closed=false;
 function close(){if(closed)return;closed=true;document.removeEventListener('keydown',key,true);overlay.remove();if(previous?.isConnected)previous.focus();onClose();}
 function key(e){e.stopImmediatePropagation();if(e.key==='Escape'){e.preventDefault();close();}else if(e.key==='Tab'){e.preventDefault();button.focus();}}
 document.addEventListener('keydown',key,true);button.onclick=close;return close;
}
export function startPhoto({modal,state,open,finish,cancel,setCleanup,viewers,onStart=()=>{},onTick=()=>{},paused=()=>false,onContext=()=>{},fx=()=>{}}){
 const items=photosForDay(state.day);let item=items[0],disposed=false,raf=0,last=0,elapsed=0,capture=0,orders=0,turn=0,phase='pick',roundTime=0,target=0,lastTarget=-1,previewToken=0;
 const $=q=>modal.querySelector(q);const labels=['귀엽게 손하트','우아하게 미소','신나게 브이'];const poseCache=new Map();
 const prompts=[['손하트 방셀로 소장하고 싶어요!','하트 포즈 한 장 부탁해요.','귀여운 손하트 버전 기다렸어요!'],['차분한 미소 버전 주세요!','우아한 표정으로 부탁해요.','편안하게 미소 짓는 사진이 좋아요.'],['승리 브이 포즈 부탁해요!','신나는 브이 버전 소장할래요!','오늘의 승리 기념으로 브이 사진 주세요!']];
 open(`<div class="photo-shell"><div class="photo-heading"><span class="eyebrow">MONTHLY PHOTO</span><h2 id="modal-title">${state.day<16?'8월':'9월'} 방셀 촬영 · 판매</h2><p id="photo-status">사진을 고르고 촬영을 시작하세요.</p></div><div class="photo-layout"><div id="photo-preview">${artHTML(item)}</div><section class="photo-panel"><div id="photo-pick"><label>이번 방셀 <select id="photo-select">${items.map(p=>`<option value="${p.id}">${escape(p.title)}</option>`).join('')}</select></label><p>촬영 5초 + 주문 6건(각 5초). 초록 구간에서 촬영하고 주문에 맞는 포즈를 골라요.</p><p>체력 −12 · 별풍선 최대 150개 · 즐겨찾기 최대 +3. 피로와 연속 활동에 따라 감소합니다.</p><button class="primary" id="photo-start">촬영 시작</button></div><div id="photo-play" hidden><div class="photo-meter"><span></span><i id="photo-pointer"></i></div><button class="primary" id="photo-shoot">사진 찍기 · SPACE</button><p id="photo-customer"></p><p id="photo-request"></p><div id="photo-orders" hidden>${labels.map((l,i)=>`<button class="choice" data-pose="${i}">${l}</button>`).join('')}</div><p id="photo-feedback" aria-live="polite"></p></div></section></div><button class="textbtn" id="photo-cancel">취소하고 돌아가기 · 보상 없음</button></div>`,{locked:true});modal.classList.add('photo-dialog');guardImages(modal);
 function preloadPoses(photo){for(const pose of PHOTO_POSES){const src=photoOrderSrc(photo.id,pose);if(poseCache.has(src))continue;const image=new Image();poseCache.set(src,{image,status:'loading'});image.onload=()=>{const entry=poseCache.get(src);if(entry)entry.status='ready';};image.onerror=()=>{const entry=poseCache.get(src);if(entry)entry.status='error';};image.src=src;}}
 function setFeedback(text,result=''){const el=$('#photo-feedback');el.textContent=text;if(result)el.dataset.result=result;else delete el.dataset.result;}
 function showRepresentative(){const host=$('#photo-preview');if(!host)return;previewToken++;delete host.dataset.result;host.innerHTML=artHTML(item);guardImages(host);}
 function showPose(pose,good){const host=$('#photo-preview'),figure=host?.querySelector('.gallery-figure'),img=figure?.querySelector('img'),caption=figure?.querySelector('figcaption');if(!host||!img||!caption)return;const src=photoOrderSrc(item.id,pose),token=++previewToken;host.dataset.result=good?'success':'error';const fallback=()=>{if(token!==previewToken)return;img.onerror=null;img.src=item.ready?item.src:FANART_PLACEHOLDER;img.alt=item.ready?item.description:'방셀 대표 이미지를 불러오지 못했습니다.';caption.textContent=item.title+' · 대표 이미지로 복구';};if(poseCache.get(src)?.status==='error'){fallback();return;}img.onerror=fallback;img.src=src;img.alt=`${item.title} · ${labels[PHOTO_POSES.indexOf(pose)]}`;caption.textContent=`${item.title} · ${labels[PHOTO_POSES.indexOf(pose)]}`;}
 preloadPoses(item);
 function cleanup(){disposed=true;previewToken++;cancelAnimationFrame(raf);document.removeEventListener('keydown',key);modal.classList.remove('photo-dialog');}
 setCleanup(cleanup);$('#photo-cancel').onclick=cancel;
 $('#photo-select').onchange=e=>{item=items.find(p=>p.id===e.target.value)||items[0];showRepresentative();preloadPoses(item);};
 function nextOrder(){if(turn>=6){const r=photoRewards(capture,orders,state.energy,state.last==='photo'?state.streak+1:1);cleanup();finish(r.score,{capture,orders,photoId:item.id});return;}showRepresentative();if(turn>0)setFeedback('');phase='orders';fx('item_ready');roundTime=0;const targets=[0,1,2].filter(x=>x!==lastTarget);target=targets[Math.floor(Math.random()*targets.length)];lastTarget=target;const viewer=viewers[(state.day+turn)%viewers.length];$('#photo-customer').textContent=viewer.type+' · '+viewer.name;$('#photo-request').textContent=prompts[target][Math.floor(Math.random()*3)];$('#photo-orders').hidden=false;$('#photo-shoot').hidden=true;modal.querySelectorAll('[data-pose]').forEach(b=>b.disabled=false);}
 function shoot(){if(phase!=='capture'||disposed||paused())return;fx('item_use');const x=(Math.sin(elapsed*Math.PI*1.5)+1)/2;capture=Math.abs(x-.5)<=.12?1:Math.abs(x-.5)<=.25?.5:0;setFeedback(capture===1?'선명한 순간을 포착했어요!':capture===.5?'좋아요! 판매를 시작해요.':'조금 흔들렸어요. 주문 응대로 만회해요!');nextOrder();}
 function key(e){if(e.code==='Space'&&phase==='capture'){e.preventDefault();if(!e.repeat)shoot();}}
 document.addEventListener('keydown',key);$('#photo-shoot').onclick=shoot;
 modal.querySelectorAll('[data-pose]').forEach(b=>b.onclick=()=>{if(disposed||phase!=='orders'||paused())return;const selectedIndex=Number(b.dataset.pose),selectedPose=PHOTO_POSES[selectedIndex],good=selectedIndex===target;showPose(selectedPose,good);if(good)orders++;onContext(good?'주문 성공! 방셀 잘 받았어요.':'이번 주문은 아쉬워요. 다음 포즈를 확인해요.');fx(good?'score':'item_use');setFeedback(good?'주문 성공':'요청과 다른 포즈',good?'success':'error');turn++;phase='feedback';roundTime=0;modal.querySelectorAll('[data-pose]').forEach(x=>x.disabled=true);});
 function tick(now){if(disposed)return;const dt=Math.min(.06,Math.max(0,(now-last)/1000));last=now;if(!document.hidden&&!paused()){onTick(dt);elapsed+=dt;roundTime+=dt;if(phase==='capture'){const x=(Math.sin(elapsed*Math.PI*1.5)+1)/2;$('#photo-pointer').style.left=`${x*100}%`;$('#photo-status').textContent=`촬영 ${Math.max(0,5-roundTime).toFixed(1)}초`;if(roundTime>=5){capture=0;nextOrder();}}else if(phase==='orders'){$('#photo-status').textContent=`주문 ${turn+1}/6 · 성공 ${orders}건 · ${Math.max(0,5-roundTime).toFixed(1)}초`;if(roundTime>=5){turn++;setFeedback('주문 시간이 지났어요.','error');phase='feedback';roundTime=0;modal.querySelectorAll('[data-pose]').forEach(b=>b.disabled=true);}}else if(phase==='feedback'&&roundTime>=.9)nextOrder();}if(!disposed)raf=requestAnimationFrame(tick);}
 $('#photo-start').onclick=()=>{if(phase!=='pick')return;onStart();fx('item_ready');showRepresentative();preloadPoses(item);phase='capture';$('#photo-pick').hidden=true;$('#photo-play').hidden=false;last=performance.now();raf=requestAnimationFrame(tick);};
}
